
import React, { useState, useCallback, useMemo } from 'react';
import { INITIAL_MERCHANTS, INITIAL_ZONES } from './constants';
import { Merchant, ServiceableZone, RouteInfo, ProposalTemplate } from './types';
import MapView from './components/MapView';
import StatsPanel from './components/StatsPanel';
import {
  Search, MapPin, Navigation, Info, Zap, ChevronRight,
  BrainCircuit, Store, Globe, Activity, ArrowUpRight,
  ExternalLink, Filter, Download, Route, MessageCircle,
  FileText, Share2, X, Check, Copy
} from 'lucide-react';
import { scanPakurForPartners, suggestZonesBasedOnDensity, getRouteLogistics, DiscoveredPartner } from './services/geminiService';

const ProposalModal: React.FC<{
  partner: Merchant | DiscoveredPartner;
  onClose: () => void;
}> = ({ partner, onClose }) => {
  const [copied, setCopied] = useState(false);
  const [proposalType, setProposalType] = useState<'appointment' | 'commercial' | 'hinglish' | 'hindi'>('appointment');

  const proposal = useMemo((): ProposalTemplate => {
    let baseMessage = '';
    let title = '';

    switch (proposalType) {
      case 'appointment':
        title = 'Appointment Request';
        baseMessage = `Hello ${partner.name}, this is the PakurFast Logistics Team (Pakur Mart).

We are scheduling strategic partnership meetings with key store owners in Pakur this week. We would like to visit your store to discuss:

1. Onboarding you as a priority stock point.
2. Discussing our 10-minute delivery network.
3. Formalizing potential commission structures.

When would be a good time for a brief 15-minute appointment?`;
        break;
      case 'commercial':
        title = 'Commercial Stock Offer';
        baseMessage = `Hello ${partner.name}, exclusive offer from PakurFast (Pakur Mart)!

We are looking to help you clear your high-value stock rapidly through our new Quick Commerce platform.

Our Offer:
- Best market prices for your inventory.
- Negotiable commission rates.
- Immediate stock uptake for our 10-minute delivery zones.

Interested in maximizing your sales this month? Let's discuss a deal.`;
        break;
      case 'hinglish':
        title = 'Hinglish Proposal';
        baseMessage = `Namaste ${partner.name}, PakurFast (Pakur Mart) ki taraf se greetings!

Hum ek naya Q-commerce platform launch kar rahe hain Pakur mein. Hum chahte hain ki aapka store hamara **Strategic Partner** bane.

Offer Highlights:
1. **Stock Clearance**: Aapka stock fast move hoga.
2. **Best Prices**: Market se behtar rates milenge.
3. **10-Min Delivery**: Hamara logicstics network aapke products ko customers tak superfast deliver karega.

Kya hum aapke store par aakar commission aur deal discuss kar sakte hain?`;
        break;
      case 'hindi':
        title = 'Hindi Proposal';
        baseMessage = `नमस्ते ${partner.name}, पाकुड़ फास्ट (पाकुड़ मार्ट) की ओर से शुभकामनाएँ!

हम पाकुड़ शहर में एक नया क्विक कॉमर्स प्लेटफॉर्म शुरू कर रहे हैं। हम चाहते हैं कि आपकी दुकान हमारे प्रमुख भागीदार (Strategic Partner) के रूप में शामिल हो।

हमारे प्रस्ताव की मुख्य बातें:
1. **स्टॉक क्लियरेंस**: हम आपके इन्वेंट्री को तेज़ी से बेचने में मदद करेंगे।
2. **उचित मूल्य**: बाज़ार में सबसे बेहतरीन दाम और कमीशन।
3. **10-मिनट डिलीवरी**: हमारा लॉजिस्टिक्स नेटवर्क आपके सामान को ग्राहकों तक मिनटों में पहुँचाएगा।

क्या हम इस सप्ताह आपकी दुकान पर आकर विस्तार से चर्चा कर सकते हैं?`;
        break;
    }

    return {
      title,
      content: baseMessage,
      whatsappMessage: encodeURIComponent(baseMessage)
    };
  }, [partner, proposalType]);

  const handleCopy = () => {
    navigator.clipboard.writeText(proposal.content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const text = `${proposal.title}\n\n${proposal.content}\n\nGenerated by PakurFast Logistics Command Center`;
    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `PakurFast_Proposal_${partner.name.replace(/\s+/g, '_')}.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const rawPhone = (partner as any).phoneNumber || (partner as any).contact;
  const hasPhone = !!rawPhone;
  const whatsappUrl = hasPhone ? `https://wa.me/${rawPhone.replace(/\D/g, '')}?text=${proposal.whatsappMessage}` : '#';

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-sm animate-in fade-in duration-300">
      <div className="bg-white rounded-[2rem] w-full max-w-2xl overflow-hidden shadow-2xl flex flex-col max-h-[90vh]">
        <div className="proposal-gradient p-8 text-white flex justify-between items-start">
          <div>
            <div className="flex items-center space-x-2 text-emerald-100 text-[10px] font-bold uppercase tracking-[0.2em] mb-2">
              <FileText className="w-4 h-4" />
              <span>Tactical Proposal</span>
            </div>
            <h2 className="text-2xl font-black tracking-tight">{proposal.title}</h2>
          </div>
          <button onClick={onClose} className="p-2 hover:bg-white/10 rounded-full transition-colors">
            <X className="w-6 h-6" />
          </button>
        </div>

        <div className="p-8 overflow-y-auto flex-1 bg-slate-50">
          <div className="flex flex-wrap gap-2 mb-6 p-1 bg-slate-200/50 rounded-xl w-fit">
            <button
              onClick={() => setProposalType('appointment')}
              className={`px-3 py-2 rounded-lg text-[10px] font-black uppercase tracking-widest transition-all ${proposalType === 'appointment' ? 'bg-white text-emerald-600 shadow-sm' : 'text-slate-500 hover:text-slate-700'}`}
            >
              Appointment (Eng)
            </button>
            <button
              onClick={() => setProposalType('commercial')}
              className={`px-3 py-2 rounded-lg text-[10px] font-black uppercase tracking-widest transition-all ${proposalType === 'commercial' ? 'bg-white text-emerald-600 shadow-sm' : 'text-slate-500 hover:text-slate-700'}`}
            >
              Stock Offer (Eng)
            </button>
            <button
              onClick={() => setProposalType('hinglish')}
              className={`px-3 py-2 rounded-lg text-[10px] font-black uppercase tracking-widest transition-all ${proposalType === 'hinglish' ? 'bg-white text-purple-600 shadow-sm' : 'text-slate-500 hover:text-slate-700'}`}
            >
              Hinglish
            </button>
            <button
              onClick={() => setProposalType('hindi')}
              className={`px-3 py-2 rounded-lg text-[10px] font-black uppercase tracking-widest transition-all ${proposalType === 'hindi' ? 'bg-white text-orange-600 shadow-sm' : 'text-slate-500 hover:text-slate-700'}`}
            >
              Hindi
            </button>
          </div>

          <div className="bg-white border border-slate-200 rounded-2xl p-6 shadow-sm mb-6">
            <h3 className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-4">Message Content</h3>
            <pre className="text-sm text-slate-700 font-sans whitespace-pre-wrap leading-relaxed italic">
              "{proposal.content}"
            </pre>
          </div>

          {!hasPhone && (
            <div className="mb-6 p-4 bg-amber-50 border border-amber-200 rounded-2xl flex items-start space-x-3">
              <Info className="w-5 h-5 text-amber-500 shrink-0 mt-0.5" />
              <p className="text-xs text-amber-800 font-medium leading-relaxed">
                Phone number not available. Please contact that store by manually visiting that store and then share the proposal.
              </p>
            </div>
          )}

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {hasPhone && (
              <div className="p-4 bg-emerald-50 rounded-xl border border-emerald-100">
                <h4 className="text-[10px] font-black text-emerald-600 uppercase mb-2">WhatsApp Action</h4>
                <a
                  href={whatsappUrl}
                  target="_blank"
                  rel="noreferrer"
                  className="flex items-center justify-center space-x-2 w-full py-3 bg-emerald-500 hover:bg-emerald-600 text-white rounded-lg font-bold text-sm transition-all shadow-md"
                >
                  <MessageCircle className="w-4 h-4" />
                  <span>Share via WhatsApp</span>
                </a>
              </div>
            )}
            <div className="p-4 bg-blue-50 rounded-xl border border-blue-100">
              <h4 className="text-[10px] font-black text-blue-600 uppercase mb-2">Internal Ops</h4>
              <button
                onClick={handleDownload}
                className="flex items-center justify-center space-x-2 w-full py-3 bg-blue-500 hover:bg-blue-600 text-white rounded-lg font-bold text-sm transition-all shadow-md"
              >
                <Download className="w-4 h-4" />
                <span>Save Local Copy</span>
              </button>
            </div>
          </div>
        </div>

        <div className="px-8 py-6 border-t border-slate-100 bg-white flex justify-between items-center">
          <button
            onClick={handleCopy}
            className="flex items-center space-x-2 text-slate-500 hover:text-slate-900 font-bold text-xs uppercase tracking-widest transition-colors"
          >
            {copied ? <Check className="w-4 h-4 text-emerald-500" /> : <Copy className="w-4 h-4" />}
            <span>{copied ? 'Copied Content' : 'Copy Content'}</span>
          </button>
          <button
            onClick={onClose}
            className="px-6 py-2 border border-slate-200 rounded-lg text-xs font-bold uppercase text-slate-600 hover:bg-slate-50 transition-colors"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};

const App: React.FC = () => {
  const [activeTab, setActiveTab] = useState<'partners' | 'map' | 'details'>('map');

  const [merchants] = useState<Merchant[]>(INITIAL_MERCHANTS);
  const [zones] = useState<ServiceableZone[]>(INITIAL_ZONES);
  const [discoveredPartners, setDiscoveredPartners] = useState<DiscoveredPartner[]>([]);
  const [aiZoneSuggestions, setAiZoneSuggestions] = useState<any[]>([]);

  const [selectedMerchant, setSelectedMerchant] = useState<Merchant | null>(null);
  const [selectedDiscovered, setSelectedDiscovered] = useState<DiscoveredPartner | null>(null);
  const [selectedZoneId, setSelectedZoneId] = useState<string | null>(null);

  const [isScanning, setIsScanning] = useState(false);
  const [isCalculatingRoute, setIsCalculatingRoute] = useState(false);
  const [routeInfo, setRouteInfo] = useState<RouteInfo | null>(null);
  const [searchQuery, setSearchQuery] = useState('');
  const [showProposal, setShowProposal] = useState(false);

  const currentYear = useMemo(() => new Date().getFullYear(), []);

  const performCityScan = async () => {
    setIsScanning(true);
    setRouteInfo(null);
    try {
      const results = await scanPakurForPartners("Daily Need Shops, Kirana, Pharmacies, and Wholesale Markets");
      setDiscoveredPartners(results.partners);
      const suggestions = await suggestZonesBasedOnDensity(merchants);
      setAiZoneSuggestions(suggestions);
    } catch (err) {
      console.error(err);
    } finally {
      setIsScanning(false);
      if (window.innerWidth < 1024) setActiveTab('partners');
    }
  };

  const handleCalculateRoute = async () => {
    const active = selectedMerchant || selectedDiscovered;
    if (!active) return;

    setIsCalculatingRoute(true);
    const info = await getRouteLogistics(active.name, active.address);
    setRouteInfo(info);
    setIsCalculatingRoute(false);
  };

  const handleExportData = () => {
    const active = selectedMerchant || selectedDiscovered;
    if (!active) return;

    const data = {
      timestamp: new Date().toISOString(),
      city: "Pakur",
      partner: active,
      logistics: routeInfo
    };

    const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `PakurFast_Partner_${active.name.replace(/\s+/g, '_')}.json`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handleSelectMerchant = useCallback((merchant: Merchant) => {
    setSelectedMerchant(merchant);
    setSelectedDiscovered(null);
    setSelectedZoneId(merchant.zoneId);
    setRouteInfo(null);
    if (window.innerWidth < 1024) setActiveTab('details');
  }, []);

  const handleSelectDiscovered = (dp: DiscoveredPartner) => {
    setSelectedDiscovered(dp);
    setSelectedMerchant(null);
    setSelectedZoneId(null);
    setRouteInfo(null);
    if (window.innerWidth < 1024) setActiveTab('details');
  };

  const filteredMerchants = merchants.filter(m =>
    m.name.toLowerCase().includes(searchQuery.toLowerCase())
  );

  const selectedAny = selectedMerchant || selectedDiscovered;

  return (
    <div className="flex flex-col h-[100dvh] bg-slate-50 text-slate-900 font-sans antialiased overflow-hidden">
      {showProposal && selectedAny && (
        <ProposalModal
          partner={selectedAny}
          onClose={() => setShowProposal(false)}
        />
      )}

      {/* Navigation */}
      <header className="bg-white border-b border-slate-200 px-4 lg:px-8 py-3 lg:py-4 flex justify-between items-center shrink-0 z-50 glass-effect">
        <div className="flex items-center space-x-10">
          <div className="flex items-baseline cursor-default group">
            <h1 className="text-xl lg:text-2xl font-black text-slate-900 tracking-tighter uppercase">Pakur</h1>
            <h1 className="text-xl lg:text-2xl font-light text-emerald-600 tracking-tighter uppercase ml-0.5 group-hover:translate-x-1 transition-transform">Fast</h1>
          </div>
          <nav className="hidden lg:flex space-x-8">
            <button className="text-[10px] font-black text-slate-900 uppercase tracking-widest border-b-2 border-emerald-500 pb-1">Command Center</button>
            <button className="text-[10px] font-black text-slate-400 hover:text-slate-600 uppercase tracking-widest transition-colors">Route Planning</button>
          </nav>
        </div>

        <div className="flex items-center space-x-2 lg:space-x-4">
          <div className="relative group hidden sm:block">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400 w-4 h-4 transition-colors group-focus-within:text-emerald-500" />
            <input
              type="text"
              placeholder="Search directory..."
              className="pl-10 pr-4 py-2 bg-slate-100 border-none rounded-xl text-xs font-medium focus:ring-2 focus:ring-emerald-500 w-40 lg:w-64 outline-none transition-all"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
            />
          </div>
          <button
            onClick={performCityScan}
            disabled={isScanning}
            className={`px-3 lg:px-6 py-2 lg:py-3 rounded-xl text-[10px] font-black uppercase tracking-widest flex items-center space-x-2 transition-all shadow-lg active:scale-95 ${isScanning ? 'bg-slate-200 text-slate-400 cursor-not-allowed' : 'bg-slate-900 text-white hover:bg-slate-800'
              }`}
          >
            <Globe className={`w-3.5 h-3.5 ${isScanning ? 'animate-spin' : ''}`} />
            <span className="hidden sm:inline">{isScanning ? 'Scanning City...' : 'Identify Potential Partners'}</span>
            <span className="sm:hidden">{isScanning ? 'Scanning...' : 'Scan'}</span>
          </button>
        </div>
      </header>

      {/* Main Workspace */}
      <main className="flex-1 flex flex-col lg:flex-row overflow-hidden relative">

        {/* Left: Partner Pipeline */}
        <div className={`
          flex-col bg-white border-r border-slate-200 shrink-0 overflow-hidden transition-all duration-300 absolute inset-0 z-20 lg:static lg:w-[360px] lg:flex
          ${activeTab === 'partners' ? 'translate-x-0 opacity-100' : '-translate-x-full opacity-0 lg:translate-x-0 lg:opacity-100'}
        `}>
          <div className="p-4 lg:p-6 flex flex-col h-full bg-slate-50/50">
            {/* Mobile-only Search in Partner View */}
            <div className="lg:hidden mb-4 relative">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400 w-4 h-4" />
              <input
                type="text"
                placeholder="Search directory..."
                className="pl-10 pr-4 py-3 bg-white border border-slate-200 rounded-xl text-sm w-full outline-none focus:ring-2 focus:ring-emerald-500 shadow-sm"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
              />
            </div>

            <div className="flex items-center justify-between mb-4 lg:mb-6 px-2">
              <h2 className="text-[10px] font-black text-slate-400 uppercase tracking-[0.2em] flex items-center">
                <Check className="w-3 h-3 mr-2 text-emerald-500" />
                Verified Active
              </h2>
              <Filter className="w-3.5 h-3.5 text-slate-300" />
            </div>

            <div className="space-y-3 overflow-y-auto pr-2 mb-8 flex-1 scrollbar-hide">
              {filteredMerchants.length > 0 ? filteredMerchants.map(merchant => (
                <div
                  key={merchant.id}
                  onClick={() => handleSelectMerchant(merchant)}
                  className={`p-4 rounded-2xl border cursor-pointer transition-all group premium-card ${selectedMerchant?.id === merchant.id
                    ? 'bg-emerald-50 border-emerald-500 shadow-md scale-[1.02]'
                    : 'bg-white border-slate-100 hover:border-slate-300'
                    }`}
                >
                  <div className="flex justify-between items-center mb-1">
                    <h3 className="font-bold text-slate-900 text-sm truncate">{merchant.name}</h3>
                    {merchant.isCollaborated && <Zap className="w-3 h-3 text-emerald-500 fill-emerald-500" />}
                  </div>
                  <p className="text-[10px] text-slate-400 mb-3 truncate">{merchant.address}</p>
                  <div className="flex items-center justify-between">
                    <span className="text-[8px] font-black text-slate-500 bg-slate-100 px-2 py-0.5 rounded uppercase">{merchant.category}</span>
                    <ArrowUpRight className="w-3.5 h-3.5 text-slate-200 group-hover:text-emerald-500 transition-colors" />
                  </div>
                </div>
              )) : (
                <div className="py-10 text-center text-slate-400">
                  <p className="text-xs">No partners found matching your search.</p>
                </div>
              )}
            </div>

            {/* AI Discovered Results */}
            <div className="pt-6 border-t border-slate-200">
              <h2 className="text-[10px] font-black text-indigo-500 uppercase tracking-[0.2em] mb-4 flex items-center px-2">
                <BrainCircuit className="w-3.5 h-3.5 mr-2" />
                Market Discovery
              </h2>
              <div className="space-y-2 max-h-[250px] overflow-y-auto pr-2 scrollbar-hide">
                {discoveredPartners.length > 0 ? (
                  discoveredPartners.map((dp, idx) => (
                    <div
                      key={idx}
                      onClick={() => handleSelectDiscovered(dp)}
                      className={`p-3 rounded-xl border transition-all cursor-pointer premium-card ${selectedDiscovered?.name === dp.name
                        ? 'border-indigo-500 bg-indigo-50 shadow-md'
                        : 'bg-white border-slate-100 hover:bg-slate-50'
                        }`}
                    >
                      <h4 className="text-xs font-bold text-slate-800">{dp.name}</h4>
                      <div className="flex items-center justify-between mt-1">
                        <span className="text-[9px] text-slate-400 italic">Potential Lead</span>
                        <ExternalLink className="w-3 h-3 text-slate-300" />
                      </div>
                    </div>
                  ))
                ) : (
                  <div className="p-6 bg-slate-100/50 rounded-2xl border border-dashed border-slate-200 text-center">
                    <Globe className="w-6 h-6 text-slate-300 mx-auto mb-2" />
                    <p className="text-[10px] text-slate-500 italic max-w-[120px] mx-auto uppercase tracking-tighter">Run full city scan to discover local stores</p>
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>

        {/* Center: Intelligence Map */}
        <div className={`
          flex-col bg-slate-100 p-4 lg:p-6 overflow-y-auto flex-1 absolute inset-0 z-10 lg:static lg:flex
          ${activeTab === 'map' ? 'flex' : 'hidden lg:flex'}
        `}>
          <StatsPanel
            totalPartners={merchants.length}
            identifiedOpportunities={discoveredPartners.length}
            coveredZones={zones.length}
          />

          <div className="flex-1 min-h-[50vh] relative bg-white rounded-[2rem] lg:rounded-[3rem] overflow-hidden shadow-2xl border border-slate-200 mt-4 lg:mt-6">
            <MapView
              zones={zones}
              merchants={merchants}
              selectedZoneId={selectedZoneId}
              onSelectMerchant={handleSelectMerchant}
            />
            {/* Map Overlay Button for Mobile (Reset) */}
            <div className="absolute bottom-6 right-6 z-[2]">
              <button className="p-3 bg-white shadow-xl rounded-full text-slate-600 hover:text-emerald-500 transition-colors">
                <Navigation className="w-5 h-5" />
              </button>
            </div>
          </div>
        </div>

        {/* Right: Partner Intelligence Detail */}
        <div className={`
          bg-slate-950 flex-col shrink-0 overflow-y-auto p-6 lg:p-10 absolute inset-0 z-30 lg:static lg:w-[440px] lg:flex transition-all duration-300
          ${activeTab === 'details' ? 'translate-x-0 opacity-100' : 'translate-x-full opacity-0 lg:translate-x-0 lg:opacity-100'}
        `}>
          {/* Mobile Back Button from Details */}
          <div className="lg:hidden mb-10">
            <button
              onClick={() => setActiveTab('partners')}
              className="flex items-center text-slate-400 hover:text-white transition-colors bg-white/5 px-4 py-2 rounded-full border border-white/10"
            >
              <ChevronRight className="w-4 h-4 rotate-180 mr-2" />
              <span className="text-xs font-black uppercase tracking-wider">Back to Pipeline</span>
            </button>
          </div>

          {selectedMerchant || selectedDiscovered ? (
            <div className="space-y-10 animate-in slide-in-from-bottom-8 duration-500 pb-20 lg:pb-0">
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <div className="flex items-center space-x-2">
                    <div className={`w-2 h-2 rounded-full ${selectedMerchant ? 'bg-emerald-500' : 'bg-indigo-500'} animate-pulse`} />
                    <span className="text-[10px] font-black text-slate-500 uppercase tracking-[0.2em]">
                      {selectedMerchant ? 'Verified Node' : 'Market Opportunity'}
                    </span>
                  </div>
                  {selectedMerchant?.isCollaborated && (
                    <span className="text-[9px] font-black text-emerald-400 bg-emerald-400/10 px-2 py-0.5 rounded-full border border-emerald-400/20">LIVE</span>
                  )}
                </div>
                <h2 className="text-3xl lg:text-4xl font-black text-white tracking-tighter leading-none">
                  {selectedMerchant ? selectedMerchant.name : selectedDiscovered?.name}
                </h2>
              </div>

              <div className="space-y-6">
                <div className="dark-glass-effect rounded-[2rem] p-8 border border-white/5">
                  <h3 className="text-[10px] font-black text-slate-500 uppercase tracking-widest mb-6">Location Assessment</h3>
                  <div className="space-y-5">
                    <div className="flex items-start space-x-4 text-sm text-slate-300">
                      <div className="p-2 bg-slate-900 rounded-lg text-slate-500 mt-1"><MapPin className="w-4 h-4" /></div>
                      <p className="font-medium leading-relaxed">
                        {selectedMerchant ? selectedMerchant.address : selectedDiscovered?.address}, Pakur
                      </p>
                    </div>

                    <a
                      href={selectedMerchant?.mapUrl || selectedDiscovered?.googleMapsUri || '#'}
                      target="_blank"
                      rel="noreferrer"
                      className="flex items-center justify-between w-full p-4 bg-white/5 hover:bg-white/10 border border-white/10 rounded-2xl group transition-all"
                    >
                      <div className="flex items-center space-x-3">
                        <Globe className="w-5 h-5 text-emerald-500" />
                        <span className="text-xs font-bold text-white uppercase tracking-wider">Google Maps Intel</span>
                      </div>
                      <ExternalLink className="w-4 h-4 text-slate-500 group-hover:text-white transition-colors" />
                    </a>
                  </div>
                </div>

                {/* Logistics Analysis Feature */}
                <div className="dark-glass-effect rounded-[2rem] p-8 border border-white/5 relative overflow-hidden">
                  {/* Subtle background glow */}
                  <div className="absolute -right-20 -top-20 w-40 h-40 bg-emerald-500/10 blur-[60px] rounded-full pointer-events-none" />

                  <h3 className="text-[10px] font-black text-slate-500 uppercase tracking-widest mb-6 flex justify-between">
                    <span>Performance Metrics</span>
                    {isCalculatingRoute && <Activity className="w-3 h-3 animate-spin text-emerald-400" />}
                  </h3>

                  {routeInfo ? (
                    <div className="space-y-6">
                      <div className="grid grid-cols-2 gap-4">
                        <div className="bg-slate-900 border border-white/5 p-4 rounded-2xl">
                          <p className="text-[8px] text-slate-500 font-bold uppercase mb-2">Distance to Node</p>
                          <p className="text-xl font-black text-white">{routeInfo.distanceKm} <span className="text-[10px] text-slate-500">KM</span></p>
                        </div>
                        <div className="bg-slate-900 border border-white/5 p-4 rounded-2xl">
                          <p className="text-[8px] text-slate-500 font-bold uppercase mb-2">Est. Drive Time</p>
                          <p className="text-xl font-black text-white">{routeInfo.estimatedTimeMins} <span className="text-[10px] text-slate-500">MINS</span></p>
                        </div>
                      </div>
                      <div className="p-4 bg-slate-900/50 rounded-2xl border border-white/5">
                        <div className="flex items-center justify-between mb-3">
                          <span className="text-[9px] font-black text-slate-500 uppercase">Feasibility Rating</span>
                          <span className={`text-[10px] font-black uppercase px-3 py-1 rounded-full ${routeInfo.feasibility === 'High' ? 'bg-emerald-500/20 text-emerald-400 border border-emerald-500/30' : 'bg-amber-500/20 text-amber-400 border border-amber-500/30'
                            }`}>
                            {routeInfo.feasibility}
                          </span>
                        </div>
                        <p className="text-xs text-slate-400 leading-relaxed italic">"{routeInfo.notes}"</p>
                      </div>
                    </div>
                  ) : (
                    <div className="py-8 text-center bg-slate-900/40 rounded-2xl border border-dashed border-white/5">
                      <Route className="w-8 h-8 text-slate-800 mx-auto mb-3" />
                      <p className="text-[10px] text-slate-500 uppercase tracking-widest font-black">Run route analysis</p>
                      <p className="text-[8px] text-slate-600 mt-1 px-4 italic">Predict delivery times based on Pakur traffic patterns</p>
                    </div>
                  )}
                </div>

                <div className="pt-4 flex flex-col space-y-4">
                  <button
                    onClick={handleCalculateRoute}
                    disabled={isCalculatingRoute}
                    className="w-full py-5 bg-emerald-600 hover:bg-emerald-500 text-white font-black rounded-2xl shadow-xl transition-all flex items-center justify-center space-x-3 disabled:opacity-50 active:scale-95 group"
                  >
                    <Route className={`w-5 h-5 group-hover:rotate-12 transition-transform ${isCalculatingRoute ? 'animate-pulse' : ''}`} />
                    <span className="text-[11px] uppercase tracking-widest">
                      {isCalculatingRoute ? 'Calculating Metrics...' : 'Analyze Logistics Route'}
                    </span>
                  </button>

                  <div className="grid grid-cols-2 gap-4">
                    <button
                      onClick={() => setShowProposal(true)}
                      className="py-4 bg-indigo-600 hover:bg-indigo-500 text-white font-black rounded-2xl transition-all flex items-center justify-center space-x-2 active:scale-95 shadow-lg group"
                    >
                      <Share2 className="w-4 h-4 group-hover:-translate-y-0.5 transition-transform" />
                      <span className="text-[10px] uppercase tracking-widest">Proposal</span>
                    </button>
                    <button
                      onClick={handleExportData}
                      className="py-4 bg-white/10 hover:bg-white/20 text-white font-black rounded-2xl border border-white/10 transition-all flex items-center justify-center space-x-2 active:scale-95"
                    >
                      <Download className="w-4 h-4" />
                      <span className="text-[10px] uppercase tracking-widest">Export</span>
                    </button>
                  </div>
                </div>
              </div>
            </div>
          ) : (
            <div className="flex-1 flex flex-col items-center justify-center text-center px-4">
              <div className="w-24 h-24 bg-white/5 rounded-[3rem] border border-white/10 flex items-center justify-center mb-8 float-animation">
                <Store className="w-10 h-10 text-slate-700" />
              </div>
              <h3 className="text-2xl font-black text-white mb-4 tracking-tight">Intelligence Ready</h3>
              <p className="text-sm text-slate-500 max-w-[280px] leading-relaxed mx-auto italic">
                Select a verified hub or lead to generate tactical logistics reports and partnership proposals.
              </p>
              {/* Mobile Hint */}
              <button
                onClick={() => setActiveTab('partners')}
                className="mt-10 px-8 py-3 bg-emerald-500 text-white rounded-full text-[10px] font-black uppercase tracking-[0.2em] lg:hidden active:scale-95 shadow-lg"
              >
                Scan Partner List
              </button>
            </div>
          )}

          {aiZoneSuggestions.length > 0 && (
            <div className="mt-12 pt-10 border-t border-white/5 pb-20 lg:pb-0">
              <h3 className="text-[10px] font-black text-emerald-500 uppercase tracking-[0.2em] mb-6 flex items-center px-2">
                <Activity className="w-3.5 h-3.5 mr-2" />
                Planning Recommendations
              </h3>
              <div className="space-y-4">
                {aiZoneSuggestions.map((s, i) => (
                  <div key={i} className="p-5 bg-white/5 border border-white/5 rounded-2xl hover:bg-white/10 transition-colors group">
                    <div className="flex justify-between items-center mb-3">
                      <span className="text-xs font-black text-white uppercase group-hover:text-emerald-400 transition-colors">{s.zoneName}</span>
                      <span className="text-[9px] font-black text-emerald-500 bg-emerald-500/10 px-2 py-0.5 rounded-full border border-emerald-500/20">{s.radiusKm} KM Hub</span>
                    </div>
                    <p className="text-[11px] text-slate-400 leading-relaxed line-clamp-2 italic">"{s.rationale}"</p>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      </main>

      {/* Mobile Bottom Navigation - Improved with Indicators and Safety */}
      <nav className="lg:hidden bg-white border-t border-slate-200 flex justify-around items-center h-20 shrink-0 z-50 px-4 pb-[env(safe-area-inset-bottom,4px)] glass-effect">
        <button
          onClick={() => setActiveTab('partners')}
          className={`flex flex-col items-center justify-center w-full h-full space-y-1.5 transition-all ${activeTab === 'partners' ? 'text-emerald-600 scale-110' : 'text-slate-400'}`}
        >
          <div className={`p-2 rounded-xl ${activeTab === 'partners' ? 'bg-emerald-50' : ''}`}>
            <Store className="w-5 h-5" />
          </div>
          <span className="text-[8px] font-black uppercase tracking-widest">List</span>
        </button>
        <button
          onClick={() => setActiveTab('map')}
          className={`flex flex-col items-center justify-center w-full h-full space-y-1.5 transition-all ${activeTab === 'map' ? 'text-emerald-600 scale-110' : 'text-slate-400'}`}
        >
          <div className={`p-2 rounded-xl ${activeTab === 'map' ? 'bg-emerald-50' : ''}`}>
            <MapPin className="w-5 h-5" />
          </div>
          <span className="text-[8px] font-black uppercase tracking-widest">Maps</span>
        </button>
        <button
          onClick={() => setActiveTab('details')}
          className={`flex flex-col items-center justify-center w-full h-full space-y-1.5 transition-all relative ${activeTab === 'details' ? 'text-emerald-600 scale-110' : 'text-slate-400'}`}
        >
          <div className={`p-2 rounded-xl ${activeTab === 'details' ? 'bg-emerald-50' : ''}`}>
            {(selectedMerchant || selectedDiscovered) && <span className="absolute top-2 right-6 w-2 h-2 bg-emerald-500 rounded-full border-2 border-white" />}
            <Zap className="w-5 h-5" />
          </div>
          <span className="text-[8px] font-black uppercase tracking-widest">Intel</span>
        </button>
      </nav>

      <footer className="hidden lg:flex bg-slate-950 border-t border-white/5 px-10 py-4 justify-between items-center text-[10px] font-black uppercase tracking-[0.2em] text-slate-500 shrink-0">
        <div className="flex items-center space-x-12">
          <span className="hover:text-emerald-500 transition-colors cursor-default">System Health: 100% Optimal</span>
          <span className="flex items-center text-slate-400"><MapPin className="w-3 h-3 mr-2" /> Pakur Node Active</span>
          <span className="text-slate-700">|</span>
          <span className="text-slate-600 whitespace-nowrap">&copy; {currentYear} Pakur Logistics Hub</span>
        </div>
        <div className="flex items-center space-x-8">
          <span className="text-emerald-600/60 font-black">Secure Tunnel Established</span>
          <div className="flex space-x-2">
            <div className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse" />
            <div className="w-1.5 h-1.5 rounded-full bg-emerald-500/50" />
            <div className="w-1.5 h-1.5 rounded-full bg-emerald-500/20" />
          </div>
        </div>
      </footer>
    </div>
  );
};

export default App;
